/**
 * Deploy CodeAuditor ke Ritual Chain (Token MockRITUAL sudah ada)
 * Jalankan dari folder ritual-codeauditor:
 *   $env:PRIVATE_KEY="..."; node deploy/deploy2.js
 */

const { ethers } = require("ethers");
const fs   = require("fs");
const path = require("path");

async function main() {
  const PRIVATE_KEY = process.env.PRIVATE_KEY;
  if (!PRIVATE_KEY) {
    console.error("❌  Set PRIVATE_KEY env var dulu");
    process.exit(1);
  }

  // Token MockRITUAL yang sudah di-deploy
  const TOKEN_ADDRESS    = "0x26c11EB567BB83d2B031af41188ECA7872CaAF07";
  const AUDIT_FEE        = ethers.parseEther("1"); // 1 mRITUAL per audit
  // Executor from TEEServiceRegistry (queried off-chain, LLM capability=1)
  const EXECUTOR_ADDRESS = "0xec6a6c7ebd08616c805e18cdea6bf9c54950c77d";
  const RPC_URL          = "https://rpc.ritualfoundation.org";
  const CHAIN_ID      = 1979n;

  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet   = new ethers.Wallet(PRIVATE_KEY.replace("0x", ""), provider);

  console.log("\n╔═══════════════════════════════════════════╗");
  console.log("║   CodeAuditor — Deploy (Step 2/2)          ║");
  console.log("╚═══════════════════════════════════════════╝\n");

  const network = await provider.getNetwork();
  console.log(`🔗  Chain ID:   ${network.chainId}`);
  if (network.chainId !== CHAIN_ID) {
    console.error(`❌  Wrong chain! Expected 1979, got ${network.chainId}`);
    process.exit(1);
  }

  const balance = await provider.getBalance(wallet.address);
  console.log(`👛  Deployer:   ${wallet.address}`);
  console.log(`💰  Balance:    ${ethers.formatEther(balance)} ETH`);
  console.log(`💎  Token:      ${TOKEN_ADDRESS}`);

  // Compile CodeAuditor.sol
  console.log("\n📦  Compiling CodeAuditor.sol...");
  const solc = require("solc");
  const source = fs.readFileSync(
    path.join(__dirname, "../contracts/src/CodeAuditor.sol"),
    "utf8"
  );

  const input = {
    language: "Solidity",
    sources: { "CodeAuditor.sol": { content: source } },
    settings: {
      outputSelection: { "*": { "*": ["abi", "evm.bytecode"] } },
      optimizer: { enabled: true, runs: 200 },
      viaIR: true,   // required to fix stack-too-deep on complex functions
    },
  };

  const out = JSON.parse(solc.compile(JSON.stringify(input)));

  if (out.errors) {
    const errs = out.errors.filter((e) => e.severity === "error");
    if (errs.length) {
      console.error("❌  Compile errors:");
      errs.forEach((e) => console.error("  ", e.formattedMessage));
      process.exit(1);
    }
    // Print warnings only
    out.errors.filter(e => e.severity === "warning").forEach(e =>
      console.warn("⚠️ ", e.message.split("\n")[0])
    );
  }

  console.log("✅  Compiled successfully");

  const compiled = out.contracts["CodeAuditor.sol"]["CodeAuditor"];
  const factory  = new ethers.ContractFactory(
    compiled.abi,
    "0x" + compiled.evm.bytecode.object,
    wallet
  );

  console.log("\n📦  Deploying CodeAuditor v4...");
  const contract = await factory.deploy(TOKEN_ADDRESS, AUDIT_FEE, EXECUTOR_ADDRESS);
  console.log(`   Tx hash: ${contract.deploymentTransaction()?.hash}`);
  console.log("   Waiting for confirmation...");
  await contract.waitForDeployment();
  const auditorAddress = await contract.getAddress();

  // Auto-deposit 0.4 RITUAL into RitualWallet for executor fees
  console.log("\n💰  Depositing 0.4 RITUAL to RitualWallet for executor fees...");
  const depositTx = await wallet.sendTransaction({
    to: auditorAddress,
    data: ethers.id("depositForFees()").slice(0, 10),
    value: ethers.parseEther("0.4"),
  });
  console.log(`   Deposit tx: ${depositTx.hash}`);
  await depositTx.wait();
  console.log("✅  RitualWallet funded with 0.4 RITUAL");
  console.log(`✅  CodeAuditor: ${auditorAddress}`);

  // Write .env.local
  const envPath = path.join(__dirname, "../.env.local");
  const envContent = [
    `# Auto-generated by deploy2.js on ${new Date().toISOString()}`,
    `NEXT_PUBLIC_AUDITOR_ADDRESS=${auditorAddress}`,
    `NEXT_PUBLIC_PAYMENT_TOKEN=${TOKEN_ADDRESS}`,
    `NEXT_PUBLIC_BACKEND_URL=http://localhost:3001`,
  ].join("\n") + "\n";

  fs.writeFileSync(envPath, envContent);
  console.log(`\n📝  .env.local written:\n${envContent}`);

  console.log("╔═══════════════════════════════════════════╗");
  console.log("║          ✅  DEPLOYMENT COMPLETE!           ║");
  console.log("╚═══════════════════════════════════════════╝");
  console.log(`\n  CodeAuditor:   ${auditorAddress}`);
  console.log(`  Payment Token: ${TOKEN_ADDRESS}`);
  console.log(`  Explorer:      https://explorer.ritualfoundation.org/address/${auditorAddress}`);
  console.log(`\n  ▶️  Sekarang jalankan: npm run dev\n`);
}

main().catch((err) => {
  console.error("\n❌  Deploy failed:", err.message || err);
  process.exit(1);
});
